version: '3.8'
services:
  web:
    build: .
    container_name: marketplace_monitoring_web
    environment:
      - FLASK_ENV=production
      - API_TOKEN=your_api_token_here
      - DATABASE_URL=sqlite:///data/monitoring.db
    volumes:
      - ./data:/app/data
      - ./backend/logs:/app/backend/logs
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
    container_name: marketplace_monitoring_frontend
    ports:
      - "80:80"
    depends_on:
      - web
