version: "3.8"
services:
  # ------------ Backend (Flask) ------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marketplace-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      # (при желании можно задать CONFIG_PATH=/app/backend/config/config.conf)
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      # Чтобы config_parser читал ваш config.conf
      - ./backend/config:/app/backend/config:ro
      # Шрифт для PDF (если лежит в backend/)
      - ./backend/DejaVuSans.ttf:/app/backend/DejaVuSans.ttf:ro
      # Куда экспортить файлы
      - ./pdf_results:/app/pdf_results
      - ./csv_results:/app/csv_results

  # ------------ Frontend (React → Nginx) ------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marketplace-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  # ------------ База данных PostgreSQL ------------
  db:
    image: postgres:13-alpine
    container_name: marketplace-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
