# docker-compose.yml
services:
  # ------------ Backend (Flask) ------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marketplace-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_started
    networks:
      - app-network
    volumes:
      # Чтобы config_parser читал ваш config.conf
      - ./backend/config:/app/backend/config:ro
      # Куда экспортить файлы
      - ./pdf_results:/app/pdf_results
      - ./csv_results:/app/csv_results

  # ------------ Frontend (React → Nginx) ------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marketplace-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      db:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - app-network
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  # ------------ База данных PostgreSQL ------------
  db:
    image: postgres:13-alpine
    container_name: marketplace-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
